name: untitled3
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5
  path: ^1.8.3
  cupertino_icons: 1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: 2.3.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

